name: guardianly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Fonts
  google_fonts: ^7.0.1

  # SVG support
  flutter_svg: ^2.1.1

  # settings
  settings_ui: ^2.0.2

  # --- ADDED THESE MISSING PACKAGES ---
  geolocator: ^13.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  # ------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  firebase_core_platform_interface: ^5.3.0

flutter:
  uses-material-design: true